// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniChallenge6WebApi.Data;

#nullable disable

namespace Day5ReviewApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113230511_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MiniChallenge6WebApi.Models.GuessIt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuessCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RandomNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuessIt");
                });
#pragma warning restore 612, 618
        }
    }
}
